# Generated by Django 4.2.10 on 2024-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_types', '0007_delete_relationtypeold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='suffix_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='suffix_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='spantype',
            name='suffix_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
